* Beehive Monitor


  This project aims to provide environmental information for a beehive
  design to encourage co-habitation of [[https://en.wikipedia.org/wiki/Chelifer_cancroides][Chelifer cancroides]], the
  house pseudoscorpion, with bees, in hopes of reducing or eliminating
  the impact of the notorious [[https://en.wikipedia.org/wiki/Varroa_destructor][varroa mite]].


** Progress

   - [X] Over the air updates.
   - [X] WIFI-Provisioning.
   - [X] General configuration.
   - [X] Finalize MQTT format.
   - [X] Finalize hardware.
   - [X] Setup deep sleep mode.
   - [ ] HTTP download of SD-card-contents.
   - [X] See if an RTC would be a useful addition. (No, I use NTP)
   - [X] See if a OLED-display would be a useful addition. (I decided not for now)


** Create a Release

   To create a release, determine the version to use and set it to an
   environment variable VERSION.

   *ATTENTION*: the version should look like vX.Y - don't forget the v!

   *ATTENTION*: make sure you are on a clean repository! Check with

   #+begin_src
   git describe --dirty
   #+end_src


   Then execute the following commands:

   #+begin_src bash
     git tag -am "$VERSION" "$VERSION"
     idf.py clean
     idf.py build
     idf.py flash
   #+end_src

   Check that the App version in the startup messages is as expected.

   Then do

   #+begin_src bash
     mkdir "releases/$VERSION"
     ./copy-release.sh "releases/$VERSION"
   #+end_src

   Commit the changes.

   Push the tags

   #+begin_src bash
   git push --tags
   #+end_src

** Column Assignment

   These are the busnumber/i2c-addresses of the 4 sensors
   per columns.

   |-----------+--------------+---------------|
   | Sensor ID | Column Place | Column Number |
   |-----------+--------------+---------------|
   |      0545 |        Top/1 | One           |
   |      0544 |            2 | One           |
   |      0445 |            3 | One           |
   |      0444 |            4 | One           |
   |-----------+--------------+---------------|
   |      0745 |        Top/1 | Two           |
   |      0744 |            2 | Two           |
   |      0645 |            3 | Two           |
   |      0644 |            4 | Two           |
   |-----------+--------------+---------------|
