* Beehive Sensor Calibration Observation Log

** Hot Cup Insulated

   I placed a hot cup into the box and blew the fan.

   Once the temperature peaked I removed the cup, and turned off the
   fan.

   Then a mishap happened, and I lost all the data leading up to this
   event - but the data I want to calibrate is the one available.

   The TESTO-values were 97.4%, 24.0C when the chamber was opened at
   the end.


** Hot Bottle Insulated

   As expected, humidity dropped due to the increasing dry
   temperature.

   At 21:43 CEST I removed the bottle and turned off the fan.

   AT 23:05 CEST the temperature was still quite divergent (between 24C and 24.8C).

   I then opened the box and pressed the measure-button on the TESTO device:

   24C, 88.1%



** <2021-10-11 Mo> Hot Bottle Insulated

   I placed a 500ml hot water bottle into the box.

   The measurement period was 10s.

   I removed the bottle and turned off the fan at <2021-10-11 Mo 16:43>


   I then conducted periodic measurements with Testo equipment.

   |-------+-------------+----------|
   |  Time | Temperature | Humidity |
   |-------+-------------+----------|
   | 16:50 |        32.3 |     28.5 |
   | 17:00 |        28.2 |     34.6 |
   | 17:10 |        26.2 |     38.1 |
   | 17:23 |        24.8 |     40.5 |
   | 17:30 |        24.3 |     41.3 |
   | 17:41 |        23.8 |     42.1 |
   | 17:50 |        23.6 |     42.4 |
   |-------+-------------+----------|
   |       |             |          |



** <2021-10-12 Di> Hot Bottle Insulated

   As the experiment yesterday was a dud due to double-browser-window
   access, I re-do the whole experiment.

   Hot water bottle and fan removed/turned off at ~11:55CEST.
